task_0:
  asd_audio_weight: 0.7
  asd_audio_window_ms: 400
  asd_confidence_threshold: 0.3
  asd_enabled: true
  asd_fallback_to_yolo: true
  asd_temporal_smoothing: 0.8
  asd_visual_weight: 0.3
  audio_path: data/audio/Canva_FR.m4a
  bbox_shift: 7
  blur_kernel_ratio: 0.06
  debug_mouth_mask: true
  ellipse_padding_factor: 0.02
  enable_pre_erosion: true
  erosion_iterations: 1
  erosion_ratio: 0.008
  expand_factor: 1.9
  mask_corner_radius: 0.15
  mask_height_ratio: 0.85
  mask_shape: ultra_wide_ellipse
  mouth_scale_factor: 1.0
  mouth_vertical_offset: 0
  result_dir: ./results
  result_name: canva_erosion_test_WITH.mp4
  upper_boundary_ratio: 0.22
  use_elliptical_mask: true
  video_path: temp_canva_150frames.mp4
  yolo_center_weight: 0.2
  yolo_conf_threshold: 0.5
  yolo_max_face_jump: 0.3
  yolo_primary_face_confidence_drop: 0.8
  yolo_primary_face_lock_threshold: 10
  yolo_size_weight: 0.3
  yolo_temporal_weight: 0.25
